### PR TITLE
Feature Request: Ignore Fail

### PR DESCRIPTION
**Pull request by AsheKR**
If there is no additional commit, there will be an error, so I would like to add a function that can skip this error.
if you have any ideas or corrections, please leave a comment

### CODE REVIEW

**Comment by R0Wi** [comment]
For me it also happened that i received an error because there haven't been commits between upstream and my fork. Usually this error should be handled here:

https://github.com/TG908/fork-sync/blob/e15fc5e857fee00f9ba8b239fc3546e4612ed0c6/src/main.ts#L20-L22

but in my case the error message was something like

> No commits between master and master

so the check didn't succeed because it expects a error message like `'No commits between ' + context.repo.owner + ':' + base + ' and ' + owner + ':' + head`.

But what i also noticed is the http error code 422 saying "Unprocessable Entity". So it might be an option to edit the mentioned line of code like so:

```javascript
if (!!error.errors && error.status == 422 && error.errors[0].message.startsWith('No commits between')) {
      console.log('No commits between ' + context.repo.owner + ':' + base + ' and ' + owner + ':' + head);
    }
```
This would be a bit more robust i think.

**Comment by TG908** [comment]
Good catch. Thank you!

**Comment by AsheKR** [comment]
@R0Wi 
I think that's a good idea!
But Some may wish the Git Action itself to fail in the event of an error.
So I just added the flag while maintaining the default behavior.

I agree that your code bit more robust. How can I put it in?

**Comment by AsheKR** [comment]
@R0Wi 
I think it's a different issue from that one. 
I think it would be good to open and apply a new issue. 👍

**Comment by R0Wi** [comment]
Agree on that. I'll open a new issue with a PR attached :-)

**Pull request merged**
